int i = 0
while(i < 100) {
	float x = RandomRange(-100.0f,100.0f)
	float y = RandomRange(-100.0f,100.0f)
	
	float ry = RandomRange(0.0f,360.0f)
	
	float rscale = RandomRange(0.1f,2.5f)
	
	float randtex = RandomRange(0,1)
	
	Object tmp
	if(randtex > 0.5f) {
		tmp = AddObject("Props\Crate.obj","Stone.mtl",x,0,y,0,ry,0,rscale)
	} else {
		tmp = AddObject("Props\Crate.obj","Crate.mtl",x,0,y,0,ry,0,rscale)
	}
	
	tmp.SetOnClick("Spawn.script")
	
	i++
}
