/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef JOHANENGINE_PRIVATE_H
#define JOHANENGINE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.4.3.22682"
#define VER_MAJOR	1
#define VER_MINOR	4
#define VER_RELEASE	3
#define VER_BUILD	22682
#define COMPANY_NAME	""
#define FILE_VERSION	"1.4.3.22682"
#define FILE_DESCRIPTION	"JohanEngine"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"Kopijregt © 2011 Dhr. J.C. Mes"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"1.4.3.22682"

#endif /*JOHANENGINE_PRIVATE_H*/
